Tutorials image upload
OpenEnergyPlatform/oeplatform pull request #675
Opened 2020-11-09 16:03 UTC by jh-RLI

This PR adds the functionality to upload images to the OEP (media root). This is used in the tutorials application. A user can upload images via drag-n-drop, C&P or file context menu while creating or editing a tutorial.

## Known Issues
- If a user uploads images in a large size, the tutorial detail view will render a huge image.
- The button for uploading images got the icon symbol as the "Insert markdown syntax for links" button.

2020-11-09 16:40 UTC, MGlauer commented
The storage path of the pictures should incorporate the `MEDIA_ROOT` setting from the security settings in some way as this is where the media is stored.

2020-11-09 16:45 UTC, jh-RLI commented
I used the "ImageField" and "upload_to=" which uses the MEDIA_ROOT by default. Seehttps://docs.djangoproject.com/en/3.1/topics/files/

2020-11-09 16:48 UTC, jh-RLI commented
I used the "ImageField" and "upload_to=" which uses the MEDIA_ROOT by default. See https://docs.djangoproject.com/en/3.1/topics/files/ .

2020-11-09 17:28 UTC, MGlauer requested changes

2020-11-09 17:28 UTC, MGlauer commented on tutorials/templates/add.html
> +                                    imageUploadEndpoint: 'http://openenergy-platform.org/api/v0/image/upload/',
The URL should not be hard-coded
```suggestion
                                    imageUploadEndpoint: '/api/v0/image/upload/',
```

2020-11-12 17:28 UTC, closed without merging

2020-11-12 19:08 UTC, jh-RLI commented
What was the problem here? @MGlauer

2020-11-12 19:53 UTC, MGlauer commented
Sorry, thought I merged it. Patched it.

2020-11-12 22:41 UTC, jh-RLI commented
Thanks :)